// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_JosueRusso.Server.DAL;

#nullable disable

namespace Parcial2_JosueRusso.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230711005256_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("PesoTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CantidadUtilizada")
                        .HasColumnType("REAL");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntradasDetalle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradasDetalle");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Mani",
                            Existencia = 50,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Pistacho",
                            Existencia = 600,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Pasas",
                            Existencia = 500,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripcion = "Ciruelas",
                            Existencia = 700,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripcion = "Mixto MPP 0.5 lb",
                            Existencia = 0,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripcion = "Mixto MPC 0.5 lb",
                            Existencia = 0,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 7,
                            Descripcion = "Mixto MPP 0.2 lb",
                            Existencia = 0,
                            Tipo = 0
                        });
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.EntradasDetalle", b =>
                {
                    b.HasOne("Parcial2_JosueRusso.Shared.Entradas", null)
                        .WithMany("EntradasDetalles")
                        .HasForeignKey("EntradasDetalle");
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.Entradas", b =>
                {
                    b.Navigation("EntradasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
