// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_JosueRusso.Server.DAL;

#nullable disable

namespace Parcial2_JosueRusso.Server.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadUtilizada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrecioCompra")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Mani",
                            Existencia = 250,
                            PrecioCompra = 8.0,
                            PrecioVenta = 15.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Pistachos",
                            Existencia = 300,
                            PrecioCompra = 15.0,
                            PrecioVenta = 30.0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Pasas",
                            Existencia = 130,
                            PrecioCompra = 10.0,
                            PrecioVenta = 25.0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripcion = "Ciruelas",
                            Existencia = 350,
                            PrecioCompra = 25.0,
                            PrecioVenta = 50.0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripcion = "Mixto MPP",
                            Existencia = 320,
                            PrecioCompra = 30.0,
                            PrecioVenta = 60.0
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripcion = "Mixto MPC",
                            Existencia = 310,
                            PrecioCompra = 30.0,
                            PrecioVenta = 60.0
                        },
                        new
                        {
                            ProductoId = 7,
                            Descripcion = "Mixto MPP",
                            Existencia = 250,
                            PrecioCompra = 25.0,
                            PrecioVenta = 50.0
                        });
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.EntradasDetalle", b =>
                {
                    b.HasOne("Parcial2_JosueRusso.Shared.Entradas", null)
                        .WithMany("entradasDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parcial2_JosueRusso.Shared.Entradas", b =>
                {
                    b.Navigation("entradasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
